{% set name = "griffe" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/griffe-{{ version }}.tar.gz
  sha256: 80dd57f694327e4dd534fa88a23b7aa784b3e15cd61351c628efd226c6247143
  patches:
    - patches/0001-windows-cli-test-patch.patch  # [win]

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - pdm
  run:
    - python
    - cached_property  # [py<38]

test:
  source_files:
    - tests
  imports:
    - griffe
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest >=6.2
    - pytest-xdist >=2.4

about:
  home: https://mkdocstrings.github.io/griffe
  doc_url: https://mkdocstrings.github.io/griffe
  dev_url: https://github.com/mkdocstrings/griffe
  summary: Signatures for entire Python programs. Extract the structure, the frame, the skeleton of your project, to generate API documentation or find breaking changes in your API.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
