{% set name = "griffe" %}
{% set version = "0.19.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/griffe-{{ version }}.tar.gz
  sha256: 3a51e53bc58c45d38d6d7b4509b41b153b506de3df99767e6f891c75d91706a5

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - pdm
  run:
    - python
    - cached-property  # [py<38]

test:
  imports:
    - griffe
    - griffe.loader
    - griffe.docstrings.parsers
    - griffe.dataclasses
  commands:
    - griffe -h  # [not win]
    - griffe griffe  # [not win]
    - pip check
  requires:
    - pip

about:
  home: https://mkdocstrings.github.io/griffe
  doc_url: https://mkdocstrings.github.io/griffe
  dev_url: https://github.com/mkdocstrings/griffe
  summary: Signatures for entire Python programs. Extract the structure, the frame, the skeleton of your project, to generate API documentation or find breaking changes in your API.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
