{% set name = "griffe" %}
{% set version = "1.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/griffe-{{ version }}.tar.gz
  sha256: 52ee893c6a3a968b639ace8015bec9d36594961e156e23315c8e8e51401fa50b

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0
  entry_points:
    - griffe = griffe:main
  skip: true  [py<39]

requirements:
  host:
    - python
    - pdm-pep517
    - pdm-backend
    - pip
  run:
    - python
    - colorama >=0.4

test:
  imports:
    - griffe
  commands:
    - griffe --help
    - griffe --version
    - pip check
  requires:
    - pip

about:
  home: https://mkdocstrings.github.io/griffe
  doc_url: https://mkdocstrings.github.io/griffe
  dev_url: https://github.com/mkdocstrings/griffe
  summary: Signatures for entire Python programs. Extract the structure, the frame, the skeleton of your project, to generate API documentation or find breaking changes in your API.
  description: |
    Griffe is a tool to extract the structure of your project to generate API documentation or find breaking changes in your API.
    It can be used to generate API documentation, to find breaking changes in your API, or to extract the structure of your project to generate API documentation.
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - bandersen23
    - dbast
